---
title: "Cellcycle analysis"
output: html_document
date: "2024-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Library construction
```{r library construction, include=FALSE}
## Define human gene lists
s.genes.human <- c("MCM5", "PCNA", "TYMS", "FEN1", "MCM2", "MCM4", "RRM1", "UNG", "GINS2", "MCM6", 
                   "CDCA7", "DTL", "PRIM1", "UHRF1", "MLF1IP", "HELLS", "RFC2", "RPA2", "NASP", 
                   "RAD51AP1", "GMNN", "WDR76", "SLBP", "CCNE2", "UBR7", "POLD3", "MSH2", "ATAD2", 
                   "RAD51", "RRM2", "CDC45", "CDC6", "EXO1", "TIPIN", "DSCC1", "BLM", "CASP8AP2", 
                   "USP1", "CLSPN", "POLA1", "CHAF1B", "BRIP1", "E2F8")

g2m.genes.human <- c("HMGB2", "CDK1", "NUSAP1", "UBE2C", "BIRC5", "TPX2", "TOP2A", "NDC80", "CKS2", 
                     "NUF2", "CKS1B", "MKI67", "TMPO", "CENPF", "TACC3", "FAM64A", "SMC4", "CCNB2", 
                     "CKAP2L", "CKAP2", "AURKB", "BUB1", "KIF11", "ANP32E", "TUBB4B", "GTSE1", "KIF20B", 
                     "HJURP", "CDCA3", "HN1", "CDC20", "TTK", "CDC25C", "KIF2C", "RANGAP1", "NCAPD2", 
                     "DLGAP5", "CDCA2", "CDCA8", "ECT2", "KIF23", "HMMR", "AURKA", "PSRC1", "ANLN", 
                     "LBR", "CKAP5", "CENPE", "CTCF", "NEK2", "G2E3", "GAS2L3", "CBX5", "CENPA")

## Convert human genes to mouse genes using biomaRt
human <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
mouse <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")

## Function to convert human gene lists to mouse gene lists
convert_genes <- function(human_genes) {
  genes <- getLDS(attributes = c("hgnc_symbol"), filters = "hgnc_symbol", values = human_genes, 
                  mart = human, attributesL = c("mgi_symbol"), martL = mouse, uniqueRows = TRUE)
  mouse_genes <- genes$MGI.symbol
  return(mouse_genes)
}

## Convert s.genes and g2m.genes to mouse genes
s.genes.mouse <- convert_genes(s.genes.human)
g2m.genes.mouse <- convert_genes(g2m.genes.human)

## Ensure all genes are present in the Seurat object
s.genes.mouse <- intersect(s.genes.mouse, rownames(seurat_object))
g2m.genes.mouse <- intersect(g2m.genes.mouse, rownames(seurat_object))

## Check the number of remaining genes
length(s.genes.mouse)
length(g2m.genes.mouse)
```
#Dimentional Recution
```{r initial_PCA, include=FALSE}
## Run PCA with the filtered gene lists
seurat_object <- RunPCA(seurat_object, features = c(s.genes.mouse, g2m.genes.mouse))
DimPlot(seurat_object, reduction = "tsne")

s.genes.mouse <- conversion_table %>% filter(human %in% s.genes.human) %>% pull(mouse)
g2m.genes.mouse <- conversion_table %>% filter(human %in% g2m.genes.human) %>% pull(mouse)
```
#Cell cycle scoring and visualization
```{r initial_PCA, include=FALSE}
## Perform cell cycle scoring
seurat_object <- CellCycleScoring(seurat_object, s.features = s.genes.mouse, g2m.features = g2m.genes.mouse, set.ident = TRUE)

## Visualize the distribution of cell cycle markers across
RidgePlot(seurat_object, features = c("C-GFP", "DsRed", "Pdgfra", "Acta2"), ncol = 2)

##Visualize for different clusters
### Define the features you want to plot
features <- c("C-GFP", "DsRed", "Pdgfra", "Acta2")

### Subset the Seurat object for cluster 1
cluster_7_object <- subset(seurat_object, idents = 7)

### Create the ridge plot for the specified features
plot <- RidgePlot(cluster_7_object, features = features, ncol = 2, group.by = "Phase") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())

### Display the plot
print(plot)

### Save the plot
output_dir <- "/Users/yutongli/Desktop/ridge_plots"
file_path <- file.path(output_dir, "Cluster_7_RidgePlot.png")
ggsave(filename = file_path, plot = plot, width = 10, height = 8, dpi = 300)
```

